language: python

python: "3.6"

jobs:
    include:
      - name: "Python 3.6 on xenial"
        dist: xenial
      - name: "Python 3.6 on bionic"
        dist: bionic

addons:
    apt:
        update: true
        packages:
            - liblapack-dev
            - liblapacke-dev

install:
    - pip install -r requirements.txt
    - travis_retry python setup.py install

script: pytest
