os: linux
language: python
python: "3.6"

jobs:
    include:
      - name: "Python 3.6 on xenial"
        dist: xenial
        addons:
            apt:
                update: true
                packages:
                    - liblapack-dev
                    - liblapacke-dev

      - name: "Python 3.6 on bionic"
        dist: bionic
        addons:
            apt:
                update: true
                packages:
                    - liblapack-dev
                    - liblapacke-dev

      - name: "Python 3.7.4 on macOS 10.14.4"
        os: osx
        osx_image: xcode11.2
        language: shell
        addons:
            homebrew:
                packages: lapack

install:
    - pip3 install -r requirements.txt
    - pip3 install pytest
    - travis_retry python3 setup.py install

script: pytest
