os: linux

language: python

python:
    - "2.7"
    - "3.6"

addons:
    apt:
        update: true
        packages:
            - liblapack-dev
            - liblapack3-dev

install:
    - ls /usr/include/*.h
    - pip install -r requirements.txt
    - travis_retry python setup.py install

script: pytest
