os:
    - linux
    - osx

language: python

python: "3.6"

addons:
    apt:
        update: true
        packages:
            - liblapack-dev
            - liblapacke-dev

install:
    - pip install -r requirements.txt
    - travis_retry python setup.py install

script: pytest
